export const properties = [
  {
    id: 1,

    ownerName: "Saho",
    propertyType: "Farm",
    bhk: "",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
  {
    id: 2,
    ownerName: "Saho",
    propertyType: "House",
    bhk: "3",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
  {
    id: 3,
    ownerName: "Saho",
    propertyType: "House",
    bhk: "3",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
  {
    id: 4,
    ownerName: "Saho",
    propertyType: "House",
    bhk: "3",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
  {
    id: 5,
    ownerName: "Saho",
    propertyType: "House",
    bhk: "3",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
  {
    id: 6,
    ownerName: "Saho",
    propertyType: "House",
    bhk: "3",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
  {
    id: 7,
    ownerName: "Saho",
    propertyType: "House",
    bhk: "3",
    city: "Surat",
    pinCode: "123456",
    address: "surat,guj",
    description: "big house",
  },
];

export const PROPERTY_TYPES = [
  {
    label: "House",
    value: "home",
  },
  {
    label: "Farm",
    value: "farm",
  },
  {
    label: "Plot",
    value: "plot",
  },
  {
    label: "Appartment",
    value: "appartment",
  },
  {
    label: "Shop",
    value: "shop",
  },
];
